/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-02-07 15:42:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sirenorder_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1612527876000L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1612525022000L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1608391752000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1608383690000L));
    _jspx_dependants.put("jar:file:/C:/Workspace/Project_Final/Dalboo/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fe_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fe_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fe_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>달보드레 | 사이렌오더</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/order/sirenorder_list.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"wrap\">\r\n");
      out.write("\t\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/nav.css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   button{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"button\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"text\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   } \r\n");
      out.write("   input[type=\"password\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"number\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   textarea {\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   select{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/header.css\">\r\n");
      out.write("<link rel = \"shortcut icon\" href = \"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\" >\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"top_banner\"></div>\r\n");
      out.write("      <div class=\"frame top_area\">\r\n");
      out.write("         <div class=\"top_logo_area\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home.do\">\r\n");
      out.write("               <img id=\"top_logo\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/logo.png\">\r\n");
      out.write("            </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"top_menu\">\r\n");
      out.write("         \t\t\r\n");
      out.write("         \t \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         \t \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              \t\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t      \t\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/login.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction join(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/join.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction owner(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/ownerLoginPage.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction myPage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/myPage.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ownerStartManage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/startUpList.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ownerMainpage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/ownerLoginPage.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<nav>\r\n");
      out.write("      <div class=\"frame nav-area\">\r\n");
      out.write("         <ul class=\"main_menu\">\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>달보드레 소개</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"introduce.bo\">달보드레</a></li>\r\n");
      out.write("                  <li><a href=\"howtofind.bo\">오시는 길</a></li>               \r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>메뉴</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"newmenu_list.cf\">신 메뉴</a></li>\r\n");
      out.write("                  <li><a href=\"coffee_list.cf\">커피</a></li>               \r\n");
      out.write("                  <li><a href=\"ade_list.cf\">음료</a></li>               \r\n");
      out.write("                  <li><a href=\"dessert_list.cf\">디저트</a></li>               \r\n");
      out.write("               </ul>                  \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>MD</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=머그컵\">머그컵</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=텀블러\">텀블러</a></li> \r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=원두\">원두</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=악세사리\">악세사리</a></li>             \r\n");
      out.write("               </ul>             \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>매장검색</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"siren.cf\">사이렌 오더</a></li>\r\n");
      out.write("                  <li><a href=\"store.etc\">매장 검색</a></li>               \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>공지&이벤트</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"notice_list.bo\">공지</a></li>\r\n");
      out.write("                  <li><a href=\"event_list.bo\">이벤트</a></li>               \r\n");
      out.write("                  <li><a href=\"nList.bo\">이달의 신메뉴</a></li>               \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>문의</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"startUpProcedureView.etc\">창업 신청</a></li>\r\n");
      out.write("                  <li><a href=\"customer_service_list.bo\">고객센터</a></li>                \r\n");
      out.write("                  <li><a href=\"faqList.etc\">FAQ</a></li>      \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </nav>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("       $(\".nav-area\").mouseover(function(){\r\n");
      out.write("           $(\".sub_menu\").stop().slideDown(200);\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       $(\".nav-area\").mouseleave(function(){\r\n");
      out.write("        $(\".sub_menu\").stop().slideUp(200);\r\n");
      out.write("       });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"content\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"sirenorder_list_area\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"bell\">\r\n");
      out.write("\t\t\t<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/orderbell.PNG\" align=\"left\">\r\n");
      out.write("\t\t\t<h2 align=\"left\">주문하기</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"sirenorder_list\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<ul class=\"order-nav-list\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"newMenu\">신메뉴</a></li> <b>|</b>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"coffee\">커피</a></li> <b>|</b>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"beverage\">에이드</a></li> <b>|</b>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"#\" class=\"dessert\">디저트</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div id=\"hotcold\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/thumb.PNG\" align=\"left\">\r\n");
      out.write("\t\t\t\t<h2 align=\"left\" class=\"menu\">추천메뉴</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div id=\"\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_e_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t<div id=\"hotcold\">\r\n");
      out.write("\t\t\t\t<img src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/thumb.PNG\" align=\"left\">\r\n");
      out.write("\t\t\t\t<h2 align=\"left\" class=\"menu\">카테고리별 메뉴</h2>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"mNum\" class=\"mNum\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"m_id\" class=\"m_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ loginUser.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"store_num\" class=\"store_num\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ store_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div id=\"hot\"></div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div id=\"btn\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_e_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/footer.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"footer\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"line\"></div>\r\n");
      out.write("         <img id=\"bottom_logo\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/dalboofooter.png\" width=\"250px\">\r\n");
      out.write("         <div id=\"notice\">\r\n");
      out.write("            (주) 달보드레 대표 홍길동<br>\r\n");
      out.write("            주소: 서울시 강남구 테헤란로 KH정보교육원 5~6층 팩스: 02-111-2222<br>\r\n");
      out.write("            본사 대표전화: 02-111-2222 가맹상담전화: 02-3333-4444 고객센터: 1544-1234<br><br>\r\n");
      out.write("            <b>COPYRIGHTⓒ 2020, ALL RIGHTS RESERVED</b>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"link\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("\"><img id=\"logo1\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/instargram.png\"></a>               \r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("\"><img id=\"logo2\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/facebook.png\"></a>               \r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("\"><img id=\"logo3\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/twitter.png\"></a>                  \r\n");
      out.write("         </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$('.coffee').on('click', function(){\r\n");
      out.write("\t\tvar stockNum = $(this).parent().find(\".mNum\").val();\r\n");
      out.write("\t\tvar store_num = $('.store_num').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"choiceCoffee.cf\",\r\n");
      out.write("\t\t\tdata: {store_num: store_num},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(data.length > 0){\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, i){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tif(i.materialAmount > 0){\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">')\r\n");
      out.write("\t\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">')\r\n");
      out.write("\t\t\t\t\t\tvar $menuImg = \"<li class='coffeelist2'><img src='resources/materialuploadFiles/\" + i.rename_filename + \"'>\";\r\n");
      out.write("\t\t\t\t\t\tvar $input = $('<input type=\"checkbox\" name=\"mCheck\" id=\"mCheck\" value=\"'+i.stock_num + '\">');\r\n");
      out.write("\t\t\t\t\t\tvar $mName = $('<label></label>').text(i.materialName);\r\n");
      out.write("\t\t\t\t\t\tvar $price = $('<p></p></div></li>').text(i.materialprice + \" won\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$li.append($menuImg);\r\n");
      out.write("\t\t\t\t\t\t$li.append($input);\r\n");
      out.write("\t\t\t\t\t\t$li.append($mName);\r\n");
      out.write("\t\t\t\t\t\t$li.append($price);\r\n");
      out.write("\t\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">');\r\n");
      out.write("\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">');\r\n");
      out.write("\t\t\t\t\tvar $msg = $('<span>').text(\"준비된 메뉴가 없습니다!\");\r\n");
      out.write("\t\t\t\t\t$li.append($msg);\r\n");
      out.write("\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$('.beverage').on('click', function(){\r\n");
      out.write("\t\tvar store_num = $('.store_num').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"choiceAde.cf\",\r\n");
      out.write("\t\t\tdata: {store_num: store_num},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(data.length > 0){\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, i){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(i.materialAmount > 0){\r\n");
      out.write("\t\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">')\r\n");
      out.write("\t\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">')\r\n");
      out.write("\t\t\t\t\t\tvar $menuImg = \"<li class='coffeelist2'><img src='resources/materialuploadFiles/\" + i.rename_filename + \"'>\";\r\n");
      out.write("\t\t\t\t\t\tvar $input = $('<input type=\"checkbox\" name=\"mCheck\" id=\"mCheck\" value=\"'+i.stock_num + '\">');\r\n");
      out.write("\t\t\t\t\t\tvar $mName = $('<label></label>').text(i.materialName);\r\n");
      out.write("\t\t\t\t\t\tvar $price = $('<p></p></div></li>').text(i.materialprice + \" won\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$li.append($menuImg);\r\n");
      out.write("\t\t\t\t\t\t$li.append($input);\r\n");
      out.write("\t\t\t\t\t\t$li.append($mName);\r\n");
      out.write("\t\t\t\t\t\t$li.append($price);\r\n");
      out.write("\t\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">');\r\n");
      out.write("\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">');\r\n");
      out.write("\t\t\t\t\tvar $msg = $('<span>').text(\"준비된 메뉴가 없습니다!\");\r\n");
      out.write("\t\t\t\t\t$li.append($msg);\r\n");
      out.write("\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('.dessert').on('click', function(){\r\n");
      out.write("\t\tvar store_num = $('.store_num').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"choiceDessert.cf\",\r\n");
      out.write("\t\t\tdata: {store_num: store_num},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(data.length > 0){\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, i){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(i.materialAmount > 0){\r\n");
      out.write("\t\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">')\r\n");
      out.write("\t\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">')\r\n");
      out.write("\t\t\t\t\t\tvar $menuImg = \"<li class='coffeelist2'><img src='resources/materialuploadFiles/\" + i.rename_filename + \"'>\";\r\n");
      out.write("\t\t\t\t\t\tvar $input = $('<input type=\"checkbox\" name=\"mCheck\" id=\"mCheck\" value=\"'+i.stock_num + '\">');\r\n");
      out.write("\t\t\t\t\t\tvar $mName = $('<label></label>').text(i.materialName);\r\n");
      out.write("\t\t\t\t\t\tvar $price = $('<p></p></div></li>').text(i.materialprice + \" won\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$li.append($menuImg);\r\n");
      out.write("\t\t\t\t\t\t$li.append($input);\r\n");
      out.write("\t\t\t\t\t\t$li.append($mName);\r\n");
      out.write("\t\t\t\t\t\t$li.append($price);\r\n");
      out.write("\t\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">');\r\n");
      out.write("\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">');\r\n");
      out.write("\t\t\t\t\tvar $msg = $('<span>').text(\"준비된 메뉴가 없습니다!\");\r\n");
      out.write("\t\t\t\t\t$li.append($msg);\r\n");
      out.write("\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('.newMenu').on('click', function(){\r\n");
      out.write("\t\tvar store_num = $('.store_num').val();\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl: \"choiceNewMenu.cf\",\r\n");
      out.write("\t\t\tdata: {store_num: store_num},\r\n");
      out.write("\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(data.length > 0){\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\t$.each(data, function(index, i){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tif(i.materialAmount > 0){\r\n");
      out.write("\t\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">')\r\n");
      out.write("\t\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">')\r\n");
      out.write("\t\t\t\t\t\tvar $menuImg = \"<li class='coffeelist2'><img src='resources/materialuploadFiles/\" + i.rename_filename + \"'>\";\r\n");
      out.write("\t\t\t\t\t\tvar $input = $('<input type=\"checkbox\" name=\"mCheck\" id=\"mCheck\" value=\"'+i.stock_num + '\">');\r\n");
      out.write("\t\t\t\t\t\tvar $mName = $('<label></label>').text(i.materialName);\r\n");
      out.write("\t\t\t\t\t\tvar $price = $('<p></p></div></li>').text(i.materialprice + \" won\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$li.append($menuImg);\r\n");
      out.write("\t\t\t\t\t\t$li.append($input);\r\n");
      out.write("\t\t\t\t\t\t$li.append($mName);\r\n");
      out.write("\t\t\t\t\t\t$li.append($price);\r\n");
      out.write("\t\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar $hot = $('#hot');\r\n");
      out.write("\t\t\t\t\t$hot.html('');\r\n");
      out.write("\t\t\t\t\tvar $ul = $('<ul class=\"coffeelist\">');\r\n");
      out.write("\t\t\t\t\tvar $li = $('<li class=\"coffeelist2\">');\r\n");
      out.write("\t\t\t\t\tvar $msg = $('<span>').text(\"준비된 메뉴가 없습니다!\");\r\n");
      out.write("\t\t\t\t\t$li.append($msg);\r\n");
      out.write("\t\t\t\t\t$ul.append($li);\r\n");
      out.write("\t\t\t\t\t$hot.append($ul);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\tfunction btnclick() {\r\n");
      out.write("\t\tvar store_num = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ store_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\tvar select_stockNum = new Array();\r\n");
      out.write("\t\tvar m_id = $('.m_id').val();\r\n");
      out.write("\t\t$('input:checkbox[name=\"mCheck\"]:checked').each(function (index) {\r\n");
      out.write("\t\t\tselect_stockNum.push($(this).val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.mNum').val(select_stockNum);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(select_stockNum.length != 0){\r\n");
      out.write("\t\t\tif(confirm(\"메뉴를 담았습니다. 바로 주문하시겠습니까?\")){\r\n");
      out.write("\t\t\t\tlocation.href=\"soCartInsertGo.cf?select_stockNum=\"+select_stockNum+\"&m_id=\"+m_id + \"&store_num=\" + store_num;\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\talert(\"메뉴를 담았습니다.\");\r\n");
      out.write("\t\t\t\tlocation.href=\"soCartInsertBack.cf?select_stockNum=\"+select_stockNum+\"&m_id=\"+m_id + \"&store_num=\" + store_num;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\talert(\"메뉴를 선택해주세요.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction soOrder() {\r\n");
      out.write("\t\tvar store_num = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ store_num }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("\t\tvar select_stockNum = new Array();\r\n");
      out.write("\t\tvar m_id = $('.m_id').val();\r\n");
      out.write("\t\tvar store_num = $('.store_num').val();\r\n");
      out.write("\t\t$('input:checkbox[name=\"mCheck\"]:checked').each(function (index) {\r\n");
      out.write("\t\t\tselect_stockNum.push($(this).val());\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$('.mNum').val(select_stockNum);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tif(select_stockNum.length != 0){\r\n");
      out.write("\t\t\tif(confirm(\"주문 하시겠습니까?\")){\r\n");
      out.write("\t\t\t\tlocation.href=\"soCartInsertGo.cf?select_stockNum=\"+select_stockNum+\"&m_id=\"+m_id + \"&store_num=\" + store_num;\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"메뉴를 선택해주세요.\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/header.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/header.jsp(14,0) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/header.jsp(14,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(25,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser && loginUser.rank_code eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<!--          \t \t\t관리자가 로그인 하였을 때 가맹주관리를 누르면 메인페이지뜸 -->\r\n");
          out.write("\t\t    \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"ownerStartManage();\">창업 신청 관리</button>\r\n");
          out.write("\t\t   \t \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"location.href='mdShipManagement.md'\">배송 관리</button>\r\n");
          out.write("\t\t   \t \t\t<br>\r\n");
          out.write("\t\t    \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"ownerMainpage();\">가맹주 관리</button>\r\n");
          out.write("\t\t   \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/header.jsp(32,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"loginBtn\" value=\"로그인\" onclick=\"login();\">\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"signBtn\" value=\"회원가입\" onclick=\"location.href='joinView.me'\">\r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("<!--                \t로그인 아예 안했을 때 점주전용 누름 -->\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"signBtn\" value=\"점주전용\" onclick=\"owner();\">\r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("              \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/common/header.jsp(45,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t      \t");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               <button class=\"top_menu_btn\" id=\"logoutBtn\" onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">로그아웃</button><br><br>\r\n");
          out.write("\t\t      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/common/header.jsp(46,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("logout");
      // /WEB-INF/views/common/header.jsp(46,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("logout.me");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/common/header.jsp(49,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser && loginUser.rank_code eq '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\r\n");
          out.write("               <button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"myPage()\">마이페이지</button>\r\n");
          out.write("\t\t      \t\r\n");
          out.write("\t\t      \t<b>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("</b>\r\n");
          out.write("\t      \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/common/header.jsp(52,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.nickName}님 환영합니다!", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_e_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_e_005fforEach_005f0_reused = false;
    try {
      _jspx_th_e_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_e_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/order/sirenorder_list.jsp(43,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f0.setVar("m");
      // /WEB-INF/views/order/sirenorder_list.jsp(43,4) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_e_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/order/sirenorder_list.jsp(43,4) '${ list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_e_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_e_005fforEach_005f0 = _jspx_th_e_005fforEach_005f0.doStartTag();
        if (_jspx_eval_e_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t");
            if (_jspx_meth_e_005fif_005f0(_jspx_th_e_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_e_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\t\t\t\t");
            int evalDoAfterBody = _jspx_th_e_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_e_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_e_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_e_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_e_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fe_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_e_005fforEach_005f0);
      _jspx_th_e_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_e_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_e_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_e_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_e_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fe_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_e_005fif_005f0_reused = false;
    try {
      _jspx_th_e_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_e_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_e_005fforEach_005f0);
      // /WEB-INF/views/order/sirenorder_list.jsp(44,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ m.materialAmount gt '0' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_e_005fif_005f0 = _jspx_th_e_005fif_005f0.doStartTag();
      if (_jspx_eval_e_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<ul class=\"coffeelist\">\r\n");
          out.write("\t\t\t\t\t<li class=\"coffeelist2\">\r\n");
          out.write("\t\t\t\t\t\t<img src=\"resources/materialuploadFiles/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ m.rename_filename }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t<label>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ m.materialName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</label>\r\n");
          out.write("\t\t\t\t\t\t\t<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ m.materialprice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" won</p>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</li>\r\n");
          out.write("\t\t\t\t</ul>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_e_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_e_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fe_005fif_0026_005ftest.reuse(_jspx_th_e_005fif_005f0);
      _jspx_th_e_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_e_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_e_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  e:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_e_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fe_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_e_005fif_005f1_reused = false;
    try {
      _jspx_th_e_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_e_005fif_005f1.setParent(null);
      // /WEB-INF/views/order/sirenorder_list.jsp(70,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_e_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ !empty loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_e_005fif_005f1 = _jspx_th_e_005fif_005f1.doStartTag();
      if (_jspx_eval_e_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t<br>\r\n");
          out.write("\t\t\t\t<input type=\"button\" id=\"add\" value='담기' onclick=\"btnclick();\">\r\n");
          out.write("\t\t\t\t<input type=\"button\" id=\"ordercf\" value='주문하기' onclick=\"soOrder();\">\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_e_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_e_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fe_005fif_0026_005ftest.reuse(_jspx_th_e_005fif_005f1);
      _jspx_th_e_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_e_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_e_005fif_005f1_reused);
    }
    return false;
  }
}
