/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2021-02-07 15:16:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class owner_005fstartup_005fapply_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/views/common/nav.jsp", Long.valueOf(1612527876000L));
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1612525022000L));
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1608383690000L));
    _jspx_dependants.put("jar:file:/C:/Workspace/Project_Final/Dalboo/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>달보드레</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/manager/owner_startup_apply_detail.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/base.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/footer.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/content.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/swiper/swiper-bundle.css\"/>\r\n");
      out.write("<script src=\"https://unpkg.com/swiper/swiper-bundle.min.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("   #my-spinner {\r\n");
      out.write("   width: 100%; height: 100%;\r\n");
      out.write("   top: 0; left: 0;\r\n");
      out.write("   display: none;\r\n");
      out.write("   opacity: .6;\r\n");
      out.write("   background: silver;\r\n");
      out.write("   position: fixed;\r\n");
      out.write("}\r\n");
      out.write("#my-spinner div {\r\n");
      out.write("   width: 100%; height: 100%;\r\n");
      out.write("   display: table;\r\n");
      out.write("}\r\n");
      out.write("#my-spinner span {\r\n");
      out.write("   display: table-cell;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   vertical-align: middle;\r\n");
      out.write("}\r\n");
      out.write("#my-spinner img {\r\n");
      out.write("   background: white;\r\n");
      out.write("   padding: 1em;\r\n");
      out.write("   border-radius: .7em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"wrap\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>nav</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/nav.css\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-3.3.1.min.js\"></script> \r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("   button{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"button\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"text\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   } \r\n");
      out.write("   input[type=\"password\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   input[type=\"number\"]{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   textarea {\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("   select{\r\n");
      out.write("      outline: none;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print( request.getContextPath() );
      out.write("/resources/css/common/header.css\">\r\n");
      out.write("<link rel = \"shortcut icon\" href = \"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\" >\r\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print( request.getContextPath() );
      out.write("/favicon.ico\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\t\r\n");
      out.write("   <header>\r\n");
      out.write("      <div class=\"top_banner\"></div>\r\n");
      out.write("      <div class=\"frame top_area\">\r\n");
      out.write("         <div class=\"top_logo_area\">\r\n");
      out.write("            <a href=\"");
      out.print( request.getContextPath() );
      out.write("/home.do\">\r\n");
      out.write("               <img id=\"top_logo\" src=\"");
      out.print( request.getContextPath() );
      out.write("/resources/images/logo.png\">\r\n");
      out.write("            </a>\r\n");
      out.write("         </div>\r\n");
      out.write("         <div class=\"top_menu\">\r\n");
      out.write("         \t\t\r\n");
      out.write("         \t \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("         \t \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("              \t\r\n");
      out.write("               ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t      ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t      \t\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t      \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   </header>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("\tfunction login(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/login.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction join(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/join.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction owner(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/ownerLoginPage.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction myPage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/myPage.me';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ownerStartManage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/startUpList.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction ownerMainpage(){\r\n");
      out.write("\t\tlocation.href='");
      out.print( request.getContextPath() );
      out.write("/ownerLoginPage.ow';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t</script>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<nav>\r\n");
      out.write("      <div class=\"frame nav-area\">\r\n");
      out.write("         <ul class=\"main_menu\">\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>달보드레 소개</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"introduce.bo\">달보드레</a></li>\r\n");
      out.write("                  <li><a href=\"howtofind.bo\">오시는 길</a></li>               \r\n");
      out.write("               </ul>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>메뉴</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"newmenu_list.cf\">신 메뉴</a></li>\r\n");
      out.write("                  <li><a href=\"coffee_list.cf\">커피</a></li>               \r\n");
      out.write("                  <li><a href=\"ade_list.cf\">음료</a></li>               \r\n");
      out.write("                  <li><a href=\"dessert_list.cf\">디저트</a></li>               \r\n");
      out.write("               </ul>                  \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>MD</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=머그컵\">머그컵</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=텀블러\">텀블러</a></li> \r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=원두\">원두</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mdMain.md?mdCategory=악세사리\">악세사리</a></li>             \r\n");
      out.write("               </ul>             \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>매장검색</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"siren.cf\">사이렌 오더</a></li>\r\n");
      out.write("                  <li><a href=\"store.etc\">매장 검색</a></li>               \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>공지&이벤트</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"notice_list.bo\">공지</a></li>\r\n");
      out.write("                  <li><a href=\"event_list.bo\">이벤트</a></li>               \r\n");
      out.write("                  <li><a href=\"nList.bo\">이달의 신메뉴</a></li>               \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("\r\n");
      out.write("               <span>문의</span>\r\n");
      out.write("               <ul class=\"sub_menu\">\r\n");
      out.write("                  <li><a href=\"startUpProcedureView.etc\">창업 신청</a></li>\r\n");
      out.write("                  <li><a href=\"customer_service_list.bo\">고객센터</a></li>                \r\n");
      out.write("                  <li><a href=\"faqList.etc\">FAQ</a></li>      \r\n");
      out.write("               </ul>            \r\n");
      out.write("            </li>\r\n");
      out.write("         </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("   </nav>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   $(document).ready(function(){\r\n");
      out.write("       $(\".nav-area\").mouseover(function(){\r\n");
      out.write("           $(\".sub_menu\").stop().slideDown(200);\r\n");
      out.write("       });\r\n");
      out.write("       \r\n");
      out.write("       $(\".nav-area\").mouseleave(function(){\r\n");
      out.write("        $(\".sub_menu\").stop().slideUp(200);\r\n");
      out.write("       });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      <div id=\"content\">\r\n");
      out.write("         <!-- 슬라이드 영역-->\r\n");
      out.write("         \r\n");
      out.write("         <div class=\"main-slide-container\">\r\n");
      out.write("             <div class=\"swiper-wrapper\">\r\n");
      out.write("               <div class=\"swiper-slide\">   \r\n");
      out.write("                   <div class=\"main-slide-img-div\">\r\n");
      out.write("                        <div><img src=\"resources/images/slideImage.JPG\" width=\"100%\" height=\"100%\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"swiper-slide\">\r\n");
      out.write("                   <div class=\"main-slide-img-div\">\r\n");
      out.write("                        <div><img src=\"resources/images/slideImage2.jpg\" width=\"100%\" height=\"100%\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"swiper-slide\">\r\n");
      out.write("                   <div class=\"main-slide-img-div\">\r\n");
      out.write("                        <div><img src=\"resources/images/slideImage3.jpg\" width=\"100%\" height=\"100%\"></div>\r\n");
      out.write("                     </div>\r\n");
      out.write("              </div>\r\n");
      out.write("             </div>\r\n");
      out.write("             <div class=\"swiper-pagination\"></div>\r\n");
      out.write("             <div class=\"main-swiper-button-next\"></div>\r\n");
      out.write("             <div class=\"main-swiper-button-prev\"></div>\r\n");
      out.write("           </div>\r\n");
      out.write("           \r\n");
      out.write("        <script>\r\n");
      out.write("          var main = new Swiper('.main-slide-container', {\r\n");
      out.write("            navigation: {\r\n");
      out.write("              nextEl: '.swiper-button-next',\r\n");
      out.write("              prevEl: '.swiper-button-prev',\r\n");
      out.write("            },\r\n");
      out.write("            autoplay: {\r\n");
      out.write("                delay: 2500,\r\n");
      out.write("                disableOnInteraction: false,\r\n");
      out.write("              }\r\n");
      out.write("          });\r\n");
      out.write("         </script>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   <!-- 여기까지 -->\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("       <h2>창업신청 내역</h2>\r\n");
      out.write("       <hr>\r\n");
      out.write("        <div id=\"startup_detail_area\">\r\n");
      out.write("        \r\n");
      out.write("       <div id=\"startup_content\">\r\n");
      out.write("               <br>\r\n");
      out.write("               <font style=\"margin-left : 15px;font-size: 25px; font-weight: bold;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sTitle }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font><br><br>\r\n");
      out.write("               <font style=\"margin-left : 15px; font-weight: bold; font-size: 22px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font><br>\r\n");
      out.write("               <font style=\"margin-left : 15px;font-size: 18px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.startDate }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</font><br>\r\n");
      out.write("               <br>\r\n");
      out.write("               <hr><br>\r\n");
      out.write("            \r\n");
      out.write("               <table>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>이름</th>\r\n");
      out.write("                     <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>연락처</th>\r\n");
      out.write("                     <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sPhone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>매장명</th>\r\n");
      out.write("                     <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.storeName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>창업 희망 지역</th>\r\n");
      out.write("                     <td>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sAddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <td colspan=\"2\"></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  <tr>\r\n");
      out.write("                     <th>내용 / 창업 계획</th>\r\n");
      out.write("                     <td>\r\n");
      out.write("                     <textarea id=\"startUpContent\" cols=\"50\" rows=\"10\" readonly>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sContent }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>   \r\n");
      out.write("                     </td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                  \r\n");
      out.write("               </table>\r\n");
      out.write("               \r\n");
      out.write("               \r\n");
      out.write("         </div>\r\n");
      out.write("         <button id=\"list\"  onclick=\"location.href='startUpList.ow'\">목록으로</button>\r\n");
      out.write("           <button  id=\"delete\" value=\"삭제\" onclick=\"deleteApply();\">삭제</button>\r\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("   \r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("   \r\n");
      out.write("        function deleteApply(){\r\n");
      out.write("               var con = confirm(\"정말 삭제하시겠습니까?\");\r\n");
      out.write("            if(con){\r\n");
      out.write("               var sNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.sNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("   \r\n");
      out.write("               location.href='deleteApply.ow?sNum=' + sNum;\r\n");
      out.write("            } else{\r\n");
      out.write("               alert('취소하셨습니다.');\r\n");
      out.write("               return false;\r\n");
      out.write("            }\r\n");
      out.write("      }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("        function statusApply(chk){\r\n");
      out.write("         console.log($(chk).val());\r\n");
      out.write("           var chkBtn = $(chk).val();\r\n");
      out.write("           var sNum = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${s.sNum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("          var con = confirm(chkBtn + \"하시겠습니까?\");\r\n");
      out.write("              if(con){\r\n");
      out.write("                    $.ajax({\r\n");
      out.write("                       url: 'startUpApplyChk.ow',\r\n");
      out.write("                       data: {sNum:sNum, \r\n");
      out.write("                             chkBtn:chkBtn},\r\n");
      out.write("                             success:function(data){\r\n");
      out.write("                          if(data == 'ok'){\r\n");
      out.write("                             alert(chkBtn + '처리되었습니다.');\r\n");
      out.write("                             location.reload();\r\n");
      out.write("                          }else{\r\n");
      out.write("                             alert(chkBtn + '에 실패했습니다.');\r\n");
      out.write("                          }\r\n");
      out.write("                       }\r\n");
      out.write("                    });\r\n");
      out.write("                    }else{\r\n");
      out.write("                       alert(\"취소하셨습니다.\");\r\n");
      out.write("                       return false;\r\n");
      out.write("                    }                              \r\n");
      out.write("         }\r\n");
      out.write("        </script>\r\n");
      out.write("        <script>\r\n");
      out.write("           $(document).ready(function(){\r\n");
      out.write("             $('#my-spinner').hide(); //첫 시작시 로딩바를 숨겨준다.\r\n");
      out.write("         })\r\n");
      out.write("         .ajaxStart(function(){\r\n");
      out.write("            $('#my-spinner').show(); //ajax실행시 로딩바를 보여준다.\r\n");
      out.write("         })\r\n");
      out.write("         .ajaxStop(function(){\r\n");
      out.write("            $('#my-spinner').hide(); //ajax종료시 로딩바를 숨겨준다.\r\n");
      out.write("         });\r\n");
      out.write("        </script>\r\n");
      out.write("        <div id='my-spinner'>\r\n");
      out.write("          <div><span>\r\n");
      out.write("             <img src='//cdnjs.cloudflare.com/ajax/libs/galleriffic/2.0.1/css/loader.gif'>\r\n");
      out.write("          </span></div>\r\n");
      out.write("         </div>\r\n");
      out.write("          \r\n");
      out.write("      </div>\r\n");
      out.write("     </div> \r\n");
      out.write("   </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/header.jsp(14,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/header.jsp(14,0) '${ pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${ pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/common/header.jsp(14,0) name = scope type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setScope("application");
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fscope_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(25,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser && loginUser.rank_code eq '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("<!--          \t \t\t관리자가 로그인 하였을 때 가맹주관리를 누르면 메인페이지뜸 -->\r\n");
          out.write("\t\t    \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"ownerStartManage();\">창업 신청 관리</button>\r\n");
          out.write("\t\t   \t \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"location.href='mdShipManagement.md'\">배송 관리</button>\r\n");
          out.write("\t\t   \t \t\t<br>\r\n");
          out.write("\t\t    \t\t<button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"ownerMainpage();\">가맹주 관리</button>\r\n");
          out.write("\t\t   \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/common/header.jsp(32,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ empty sessionScope.loginUser }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"loginBtn\" value=\"로그인\" onclick=\"login();\">\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"signBtn\" value=\"회원가입\" onclick=\"location.href='joinView.me'\">\r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("<!--                \t로그인 아예 안했을 때 점주전용 누름 -->\r\n");
          out.write("               <input type=\"button\" class=\"top_menu_btn\" id=\"signBtn\" value=\"점주전용\" onclick=\"owner();\">\r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("               \r\n");
          out.write("              \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/common/header.jsp(45,15) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t      \t");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("               <button class=\"top_menu_btn\" id=\"logoutBtn\" onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logout}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">로그아웃</button><br><br>\r\n");
          out.write("\t\t      ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/common/header.jsp(46,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("logout");
      // /WEB-INF/views/common/header.jsp(46,9) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("logout.me");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/common/header.jsp(49,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginUser && loginUser.rank_code eq '1'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\t\r\n");
          out.write("               <button class=\"top_menu_btn\" id=\"MypageBtn\" onclick=\"myPage()\">마이페이지</button>\r\n");
          out.write("\t\t      \t\r\n");
          out.write("\t\t      \t<b>");
          if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fif_005f3, _jspx_page_context))
            return true;
          out.write("</b>\r\n");
          out.write("\t      \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
      // /WEB-INF/views/common/header.jsp(52,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginUser.nickName}님 환영합니다!", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/manager/owner_startup_apply_detail.jsp(138,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ s.sConfirm eq '대기' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <button id=\"accept\" value=\"승인\" onclick=\"statusApply(this);\">승인</button>\r\n");
          out.write("             <button id=\"refusal\" value=\"거절\" onclick=\"statusApply(this);\">거절</button>\r\n");
          out.write("         ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
